In [1]:
import numpy as np

In [37]:
int_text = [x for x in range(1, 21)]

batch_size, seq_length = 3,2
print(int_text)

characters_per_batch = batch_size * seq_length
n_batches = len(int_text) // characters_per_batch

# Drop non-complete batches
int_text = int_text[:n_batches * characters_per_batch]
print(int_text)

#transform int_text to a numpy.array
int_text = np.array(int_text)
print(int_text)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [38]:
# Reshape into n_seqs rows
int_text = int_text.reshape(batch_size,-1)
print(int_text.shape)
print(int_text)

(3, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [39]:
int_text = np.split(int_text, n_batches, 1)
int_text = np.array(int_text)

In [40]:
print(type(int_text))

<class 'numpy.ndarray'>


In [41]:
print(int_text)

[[[ 1  2]
  [ 7  8]
  [13 14]]

 [[ 3  4]
  [ 9 10]
  [15 16]]

 [[ 5  6]
  [11 12]
  [17 18]]]


In [ ]:
# [[[ 1  2]
#   [ 7  8]
#   [13 14]]

#  [[ 3  4]
#   [ 9 10]
#   [15 16]]

#  [[ 5  6]
#   [11 12]
#   [17 18]]]